# Generated by Django 2.2.8 on 2019-12-12 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191212_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='app.User'),
        ),
    ]
