# Generated by Django 2.2.8 on 2019-12-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191212_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user_task',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
