# Generated by Django 2.2.8 on 2019-12-12 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191212_0822'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Task',
            new_name='Task',
        ),
    ]
